# Generated by Django 4.2.8 on 2023-12-09 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PollModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('p1', models.CharField(max_length=30)),
                ('p2', models.CharField(max_length=30)),
                ('p3', models.CharField(max_length=30)),
                ('p1c', models.IntegerField(default=0)),
                ('p2c', models.IntegerField(default=0)),
                ('p3c', models.IntegerField(default=0)),
            ],
        ),
    ]
